Added Working Tab code and turned off app functionality
Error with code :-
06-30 10:17:01.907 1810-1810/yajnab.com.moneymanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{yajnab.com.moneymanager/yajnab.com.moneymanager.MainActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at yajnab.com.moneymanager.MainActivity.onCreate(MainActivity.java:69)
                                                                           at android.app.Activity.performCreate(Activity.java:5104)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:137) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
06-30 10:32:28.551 1942-1942/yajnab.com.moneymanager E/Trace: error opening trace file: No such file or directory (2)